# Copyright (c) 2025 Green Wave Team
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# Filename: smartmodels.yaml
openapi: "3.0.0"
info:
  title: "Smart Data Models"
  version: "1.0.0"
  description: "Data Models for monitoring air quality, carbon footprint and traffic impact based on FIWARE Smart Data Models."

paths: {} # We only define schemas, API paths are not needed.

components:
  schemas:
    # --- Definition of entities ---

    # 1. Device entity: Use standard definition
    Device:
      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/model.yaml#/Device"

    # 2. Building entity: Use standard definition
    Building:
      $ref: "https://smart-data-models.github.io/dataModel.Building/Building/model.yaml#/Building"

    # 3. AirQualityObserved entity: Extended with relationships
    AirQualityObserved:
      allOf: # Inherit all properties from the standard model
        - $ref: "https://smart-data-models.github.io/dataModel.Environment/AirQualityObserved/model.yaml#/AirQualityObserved"
        - type: object
          properties:
            # Explicitly define 'refDevice' as a Relationship
            refDevice:
              description: "A reference to the device which made this observation."
              x-ngsi: # Extension for NGSI-LD tool
                type: "Relationship"
                model: "https://smart-data-models.github.io/dataModel.Device/Device/model.yaml#/Device"
              $ref: "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/EntityIdentifierType"

    # 4. CarbonFootprint entity: Extended with relationships
    CarbonFootprint:
      allOf: # Inherit all properties from the standard model
        - $ref: "https://smart-data-models.github.io/dataModel.Environment/CarbonFootprint/model.yaml#/CarbonFootprint"
        - type: object
          properties:
            # Explicitly define 'refBuilding' as a Relationship
            refBuilding:
              description: "A reference to the building this carbon footprint report belongs to."
              x-ngsi: # Extension for NGSI-LD tool
                type: "Relationship"
                model: "https://smart-data-models.github.io/dataModel.Building/Building/model.yaml#/Building"
              $ref: "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/EntityIdentifierType"
    # 5. RoadSegment entity: Represents a road segment
    RoadSegment:
      $ref: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/model.yaml#/RoadSegment"

    # 6. TrafficEnvironmentImpact entity: Describes the environmental impact of traffic.
    TrafficEnvironmentImpact:
      allOf:
        - $ref: "https://smart-data-models.github.io/dataModel.Environment/TrafficEnvironmentImpact/model.yaml#/TrafficEnvironmentImpact"
        - type: object
          properties:
            # Define the relationship to the road segment it is describing.
            refRoadSegment:
              description: "A reference to the road segment where the traffic impact is measured."
              x-ngsi:
                type: "Relationship"
                model: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/model.yaml#/RoadSegment"
              $ref: "https://smart-data-models.github.io/data-models/common-schema.json#/definitions/EntityIdentifierType"

    # 7. TrafficFlowObserved entity: Minimal SUMO-derived traffic flow metrics
    TrafficFlowObserved:
      type: object
      description: "Traffic flow observation entity containing real-time metrics from SUMO simulation: queue lengths, vehicle count, and average speed."
      required:
        - id
        - type
      properties:
        id:
          description: "Unique identifier of the entity"
          type: string
          format: uri
          example: "urn:ngsi-ld:TrafficFlowObserved:4066470692"
          x-ngsi:
            type: Property
        type:
          description: "NGSI Entity type. Must be 'TrafficFlowObserved'"
          type: string
          enum:
            - TrafficFlowObserved
          x-ngsi:
            type: Property
        dateObservedFrom:
          description: "Observation period start time"
          type: string
          format: date-time
          example: "2025-11-25T10:00:00Z"
          x-ngsi:
            type: Property
        dateObservedTo:
          description: "Observation period end time"
          type: string
          format: date-time
          example: "2025-11-25T10:01:00Z"
          x-ngsi:
            type: Property
        queues:
          description: "Queue lengths per lane/direction (array of integers)"
          type: array
          items:
            type: integer
            minimum: 0
          example: [2, 1]
          x-ngsi:
            type: Property
        vehicleCount:
          description: "Total number of vehicles observed during the period"
          type: integer
          minimum: 0
          example: 5
          x-ngsi:
            type: Property
        avgSpeed:
          description: "Average vehicle speed in meters per second"
          type: number
          format: float
          minimum: 0
          example: 8.5
          x-ngsi:
            type: Property
            unitCode: "MTS"
        refRoadSegment:
          description: "Reference to the road segment where this observation was made"
          type: string
          format: uri
          example: "urn:ngsi-ld:RoadSegment:4066470692"
          x-ngsi:
            type: Relationship
            model: "https://smart-data-models.github.io/dataModel.Transportation/RoadSegment/model.yaml#/RoadSegment"
